apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 007259615064.dkr.ecr.us-east-1.amazonaws.com/mysql:v1
    ports:
    - containerPort: 3306