apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: web
  labels:
    app: employees
spec:
  containers:
  - name: web
    image: 007259615064.dkr.ecr.us-east-1.amazonaws.com/employees:v1
    ports:
    - containerPort: 8080