apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web
        image: 007259615064.dkr.ecr.us-east-1.amazonaws.com/employees:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.mysql.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "admin"
        - name: DBPWD
          value: "admin123"
        - name: DATABASE
          value: "employees"